---
- name: Run HTTPD server in podman
  hosts: podman
  tasks:
    - name: Include the podman role
      ansible.builtin.include_role:
        name: fedora.linux_system_roles.podman

    - name: Create our index.html content
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: "{{ httpd_index_path }}/index.html"
        mode: "0644"
      when: httpd_enabled_state

    - name: Remove the index.html content
      ansible.builtin.file:
        path: "{{ httpd_index_path }}/index.html"
        state: absent
      when: not httpd_enabled_state
